// export type TCategory = typeof categories;
export type TClassification = typeof classifications;
export type TClassificationKey = keyof TClassification;

export const classifications = {
  "Area Management": "إدارة المناطق",
  Revenge: "انتقام",
  Towers: "ابراج",
  Thriller: "اثارة",
  Ascension: "ارتقاء",
  Spirits: "ارواح",
  Fashion: "ازياء",
  Myths: "اساطير",
  Weekly: "اسبوعي",
  Ghosts: "اشباح",
  Oppression: "اضطهاد",
  Revival: "اعادة احياء",
  "Re-research": "اعادة بحث",
  Aging: "اعمار",
  Economy: "اقتصاد",
  Academy: "اكاديمية",
  Action: "اكشن",
  Machines: "الات",
  "Full Colors": "الألوان الممتلئة",
  Survival: "البقاء على قيد الحياة",
  "Reverse Harem": "الحريم العكسي",
  "School Life": "الحياة المدرسية",
  "Daily Life": "الحياة اليومية",
  Pets: "الحيوانات الأليفة",
  "Time Travel": "السفر عبر الزمن",
  Games: "العاب",
  "Electronic Games": "العاب الكترونية",
  "Traditional Games": "العاب تقليدية",
  "Video Games": "العاب فيديو",
  Medieval: "العصور الوسطى",
  Mystery: "الغموض",
  "Monster Girl": "الفتاة الوحش",
  "Military Arts": "الفنون العسكرية",
  Outlaws: "المخالفون للقانون",
  Deities: "الهة",
  "Virtual Reality": "الواقع الافتراضي",
  Mecha: "اليات",
  "Evil Woman": "امرأة شريرة",
  Ecchi: "ايتشي",
  Isekai: "ايسكاي",
  Adult: "بالغ",
  Superhero: "بطل خارق",
  "Unusual Hero": "بطل غير اعتيادي",
  "Mad Hero": "بطل مجنون",
  "Monster Hero": "بطل وحش",
  "Post-Apocalyptic": "بعد الكارثة",
  Police: "بوليسي",
  Historical: "تاريخي",
  Embodiment: "تجسيد",
  Update: "تحديث",
  Detective: "تحري",
  Investigation: "تحقيق",
  Planning: "تخطيط",
  Training: "تدريب",
  Suspense: "تشويق",
  "Art Coloring": "تلوين رسم",
  "Official Coloring": "تلوين رسمي",
  "Amateur Coloring": "تلوين هواة",
  Reincarnation: "تناسخ",
  Dragons: "تنانين",
  Delinquents: "جانحون",
  Crime: "جريمة",
  "Gender Bender": "جندر بندر",
  "Award-Winning": "حائز على جائزة",
  Modern: "حديث",
  War: "حرب",
  Harem: "حريم",
  Animals: "حيوانات",
  Supernatural: "خارق",
  Fantasy: "خيال",
  "Science Fiction": "خيال علمي",
  Drama: "دراما",
  Bloody: "دموى",
  Mature: "راشد",
  Horror: "رعب",
  "Arabic Novel": "رواية عربية",
  Novel: "رواية",
  Romance: "رومانسي",
  Sports: "رياضة",
  Farming: "زراعة",
  "Space-Time": "زمكاني",
  Dungeons: "زنزانات",
  Zombies: "زومبي",
  Samurai: "ساموراي",
  Psychopath: "سايكوباث",
  Magic: "سحر",
  Poison: "سم",
  Political: "سياسي",
  Seinen: "سينين",
  "Slice of Life": "شريحة من الحياة",
  Shoujo: "شوجو",
  Shounen: "شونين",
  Demons: "شياطين",
  Polishing: "صقل",
  Cooking: "طبخ",
  Medical: "طبي",
  Exorcism: "طرد الارواح الشريرة",
  Family: "عائلي",
  "Different World": "عالم مختلف",
  "Office Worker": "عامل مكتبي",
  Military: "عسكري",
  "Modern Era": "عصر حديث",
  Psychology: "علم نفس",
  Violence: "عنف",
  "Martial Arts": "فنون الدفاع عن النفس",
  Victorian: "فيكتوري",
  Combat: "قتال",
  Superpower: "قوة خارقة",
  Aliens: "كائنات فضائية",
  Comedy: "كوميديا",
  Comic: "كوميك",
  "Post-Apocalypse": "ما بعد نهاية العالم",
  Tragedy: "ماساة",
  Mafia: "مافيا",
  Manga: "مانجا",
  Manhua: "مانهوا",
  "Story Collection": "مجموعة قصص",
  School: "مدرسة",
  Werewolf: "مستذئب",
  Vampires: "مصاصي الدماء",
  Adventure: "مغامرة",
  Adapted: "مقتبسة",
  Angels: "ملائكة",
  Murim: "موريم",
  Music: "موسيقى",
  Nobility: "نبالة",
  System: "نظام",
  Psychological: "نفسى",
  "End of the World": "نهاية العالم",
  Ninja: "نينجا",
  Engineering: "هندسة",
  Hobby: "هواه",
  Obsession: "هوس",
  Monsters: "وحوش",
  "One-Shot": "ون شوت",
  Webtoon: "ويب تون",
} as const;
